# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab71f83541cc4d5026aac9623df152bc5e8c55ea822af0cfbeba14324c8589e98192580da395d58deaf7cc27b04259485ee49878880e6229c83ea39beaa37d1

test:
  secret_key_base: 659fe11245450d3246ac68464686c6f5ac1944e72e209fd31205c6d2618d7a59100520cba9c360d0ec9024a5e2737567304ec59f51c9aa588878a61727615759

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
